services:
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-development
    environment:
      HOST: ${HOST}
      PORT: ${DEV_PORT}
      HTTPS_ENABLED: ${DEV_HTTPS_ENABLED}
      DATABASE_URL: ${DATABASE_URL}
      MIGRATION_DATABASE_URL: ${MIGRATION_DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      ALLOWED_ORIGINS: ${DEV_ALLOWED_ORIGINS}
    ports:
      - "${DEV_HTTP_EXTERNAL_PORT}:${DEV_PORT}"
    restart: unless-stopped
